---
- name: Creating Bigbrain user
  user:
    name: "{{ bigbrain_user }}"
    shell: /bin/bash
    group: "{{ bigbrain_user }}"
    append: yes


- name: Creating install directory
  file:
    path: /ebs/bigbrain_jars
    state: directory
    owner: "{{ bigbrain_user }}"
    group: "{{ bigbrain_user }}"
    recurse: yes
    mode: 0755
