---
- name: Download bbciutils from Download Server
  get_url: 
    url: 'http://downloads.razorthink.net/bigbrain/py-libs/{{item}}'
    dest: '/etc/ansible/roles/ansible-role-IDE-setup/files/{{item}}'
  with_items:
  - bbcliutils-0.1-py2.py3-none-any.whl
  - bigbrain_python_sdk-0.0.1-py3-none-any.whl
  - cookbook_macros-0.1-py2.py3-none-any.whl
  - model_factory-0.1-py3-none-any.whl
  - model_optimiser-0.1-py3-none-any.whl
  - rztdl-0.1.5-py3-none-any.whl
  - rztfe-0.1-py2.py3-none-any.whl
  delegate_to: 127.0.0.1
  become: true
  become_method: sudo

- name: Copying Whl files to Destination Server
  copy:
    src: '/etc/ansible/roles/ansible-role-IDE-setup/files/{{item}}'
    dest: '/tmp/{{item}}'
  with_items:
  - bbcliutils-0.1-py2.py3-none-any.whl
  - bigbrain_python_sdk-0.0.1-py3-none-any.whl
  - cookbook_macros-0.1-py2.py3-none-any.whl
  - model_factory-0.1-py3-none-any.whl
  - model_optimiser-0.1-py3-none-any.whl
  - rztdl-0.1.5-py3-none-any.whl
  - rztfe-0.1-py2.py3-none-any.whl

- name: Installing all the Python Packages
  shell: pip3 install /tmp/*.whl

- name: Upgrade Tensorflow
  pip:
    name: tensorflow
    extra_args: --upgrade
 
- name: Download IDE Jar from Download Server
  get_url:
    url: http://downloads.razorthink.net/bigbrain/docker/ide-1.0-SNAPSHOT.jar
    dest: /etc/ansible/roles/ansible-role-IDE-setup/files/ide-1.0-SNAPSHOT.jar
  delegate_to: 127.0.0.1

- name: Copying IDE Jar to the Remote Server
  copy: 
    src: /etc/ansible/roles/ansible-role-IDE-setup/files/ide-1.0-SNAPSHOT.jar
    dest: /ebs/bigbrain_jars
    become: true
    become_user: "{{ bigbrain_user }}"

- name: Copying IDE Startup Script
  template:
    src: start-ide.sh.j2
    dest: "/home/{{ bigbrain_user }}/start-ide.sh"

- name: Starting IDE Jar
  shell: bash -x /home/{{ bigbrain_user }}/start-ide.sh
  become: true
  become_user: "{{ bigbrain_user }}"
  async: 2592000
  poll: 0

